[package]
name = "tenet-sectors"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "tenet_sectors"
path = "src/lib.rs"

[features]
default = []
racah-generated = ["racah/cgc-gen"]

[dependencies]
smallvec = { version = "1", features = ["const_generics", "union"] }
num-complex = "0.4"
num-traits = "0.2"
racah = { git = "https://github.com/Ryo-wtnb11/racah", rev = "cc1c7427e33ba944247e43e361d4c0e0eeaef6d8" }
