include!("block_structure/block_key.rs");
include!("block_structure/sector_structure.rs");
include!("block_structure/degeneracy.rs");
include!("block_structure/content.rs");
include!("block_structure/structure.rs");
include!("block_structure/intern.rs");
include!("block_structure/validated.rs");
include!("block_structure/storage_injective.rs");
include!("block_structure/coupled_regions.rs");
